openapi: 3.0.1
info:
  contact:
    name: Toast developer support
  description: Returns a restaurant's availability to accept online orders.
  title: Restaurant Availability Service API
  version: 1.0.1
servers:
- url: https://toast-api-server/restaurant-availability/v1
tags:
- name: Restaurant availability
paths:
  /availability:
    get:
      description: |
        Returns a restaurant's current availability to accept online orders. A restaurant's availability is either `ONLINE` or `OFFLINE`. When a restaurant is offline, you can still place orders via the orders API, however Toast support recommends waiting until the restaurant's status is online.
      operationId: availabilityGet
      parameters:
      - description: The Toast platform GUID of the restaurant that is the context
          for this operation.
        example: 00000000-05f4-55a4-0000-0000020f4be3
        in: header
        name: Toast-Restaurant-External-ID
        required: true
        schema:
          type: string
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/RestaurantAvailability"
          description: Successful operation
      security:
      - oauth2:
        - restaurants:read
      summary: Get online ordering availability
      tags:
      - availability
components:
  schemas:
    RestaurantAvailability:
      description: |
        A representation of the restaurant's online ordering availability.
      example:
        reason: reason
        reasonKey: AVAILABILITY_ONLINE
        restaurantGuid: restaurantGuid
        status: ONLINE
      properties:
        restaurantGuid:
          description: |
            The Toast platform GUID of the restaurant location.
          type: string
        status:
          description: "The restaurant's online ordering availability status. The\
            \ `status` value can be: \n* `ONLINE` - The restaurant's auto-fire device\
            \ is approving online orders. \n* `OFFLINE` - The restaurant's auto-fire\
            \ device has stopped approving online orders.\n"
          enum:
          - ONLINE
          - OFFLINE
          type: string
        reasonKey:
          description: "The machine-readable reason why the restaurant is available\
            \ or unavailable to accept online orders. The `reasonKey` value can be:\
            \ \n* `AVAILABILITY_ONLINE` \n* `AVAILABILITY_OFFLINE`\n"
          enum:
          - AVAILABILITY_ONLINE
          - AVAILABILITY_OFFLINE
          type: string
        reason:
          description: |
            The human-readable reason why the restaurant is available or unavailable to accept online orders.
          type: string
      type: object
  securitySchemes:
    oauth2:
      description: "Access to Toast APIs, specific endpoints, \nand specific API endpoint\
        \ operations is \ncontrolled by the scopes that are associated \nwith your\
        \ API account. \nA full reference for Toast API scopes and \ntheir capabilities\
        \ can be found in the\n[_Toast Developer Guide_](https://doc.toasttab.com/doc/devguide/apiScopes.html).\n"
      flows:
        clientCredentials:
          scopes:
            restaurants:read: |
              Allows reading from the restaurant availability API.
          tokenUrl: https://toast-api-server/authentication/v1/authentication/login
      type: oauth2
x-original-swagger-version: "2.0"
