openapi: 3.0.1
info:
  contact:
    name: Toast developer support
  description: "Returns information about the Toast restaurants that a partner \n\
    API client can access.\n"
  title: Partners API
  version: 1.0.1
servers:
- url: https://toast-api-server/partners/v1
tags:
- name: Partners
paths:
  /restaurants:
    get:
      description: "Returns an array of `PartnerAccessExternalRep` \nobjects that\
        \ contain information about the Toast restaurants that your partner \nAPI\
        \ client can access. If a `lastModified` date is specified, the API returns\
        \ \nall objects that were created or modified after that date.\n"
      operationId: restaurantsGet
      parameters:
      - description: "Limits the return data to restaurants that changed their \n\
          access configuration for a partner API client after a \nspecific date and\
          \ time.\n\nRestaurants returned either:\n\n* Gave access to a partner API\
          \ client for a partner \n  integration service after a specific date and\
          \ time.\n\n* Modified the configuration for a partner integration \n  after\
          \ a specific date and time. \n\nYou must specify the date and time as a\
          \ UTC timestamp in \nISO 8601 format, for example: \n`2020-03-01T00:00:00.000-0000`.\
          \ URL encode the timestamp. \nFor example, `2020-03-01T00%3A00%3A00.000-0000`.\n"
        in: query
        name: lastModified
        schema:
          format: date
          type: string
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: "#/components/schemas/PartnerAccessExternalRep"
                type: array
          description: Returns the list of external partner accesses
        "403":
          content: {}
          description: "Your Toast API client does not have permission to use the\
            \ \n`/restaurants` endpoint.\n"
      security:
      - oauth2: []
      summary: Get accessible restaurants
  /connectedRestaurants:
    get:
      description: |
        Returns a `PaginatedResponse` object that contains a paginated array of
        the restaurants that have connected to your integrated partner service.
        Information about each restaurant is included in the array as a
        `PartnerAccessExternalRep` object.

        Use the `pageSize` query parameter to control the number of restaurants
        returned in the response. The default `pageSize` is 100. The maximum
        `pageSize` is 200.

        Request the next page of restaurant information using the `pageToken`
        query parameter. You get the token string for the next page from the
        `nextPageToken` value of the `PaginatedResponse` object for a page of
        results. You can also get the token strings for the first and next pages
        from [the `link` response header
        fields](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Link).
      operationId: connectedRestaurantsGet
      parameters:
      - description: "Limits the return data to restaurants that changed their access\n\
          configuration for your partner service after a specific date and\ntime.\
          \ You can use this parameter to identify new or updated\nrestaurants connected\
          \ to your partner service.\n\nThe restaurants included in the response data\
          \ either:\n\n* Gave access to your integrated partner service after a specific\n\
          \  date and time.\n\n* Modified the configuration for your integrated partner\
          \ service after\n  a specific date and time. \n\nYou must [specify the date\
          \ and\ntime](https://doc.toasttab.com/doc/devguide/api_dates_and_timestamps.html)\n\
          as a UTC timestamp in ISO 8601 format, for example:\n`2020-03-01T00:00:00.000-0000`.\
          \ URL-encode the timestamp. For\nexample, `2020-03-01T00%3A00%3A00.000-0000`.\n"
        in: query
        name: lastModified
        schema:
          format: date
          type: string
      - description: |
          Controls the number of `PartnerAccessExternalRep` objects that the
          endpoint will return in each page of response data. The default page
          size is `100`. The maximum page size is `200`.
        in: query
        name: pageSize
        schema:
          maximum: 200
          minimum: 1
          type: integer
      - description: |
          Returns a specific set of restaurants in the response value. You get
          the token string for the next page of connected restaurants from the
          `nextPageToken` value of the `PaginatedResponse` object for a page
          of results. You can also get the token strings for the first and
          next pages from [the `link` response header
          fields](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Link).
        in: query
        name: pageToken
        schema:
          type: string
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: "#/components/schemas/PaginatedResponse"
                type: array
          description: |
            Returns a `PaginatedResponse` object that contains a paginated array of
            the restaurants that have connected to your integrated partner service.
        "403":
          content: {}
          description: "Your Toast API client does not have permission to use the\
            \ \n`/connectedRestaurants` endpoint.\n"
      security:
      - oauth2: []
      summary: Get connected restaurants
components:
  schemas:
    PartnerAccessExternalRep:
      description: |
        Information about a Toast platform restaurant.
      example:
        deleted: true
        locationName: 123 Main Street
        createdByEmailAddress: clefebvre@mainstreetcafe.com
        externalRestaurantRef: externalRestaurantRef
        createdDate: 1643858534451
        managementGroupGuid: bdfda703-2a83-4e0f-9b8a-8ea0ee6cab79
        restaurantName: Main Street Cafe
        isoModifiedDate: 2023-03-12T08:32:34.008Z
        modifiedDate: 1678846869551
        isoCreatedDate: 2022-05-17T10:21:38.008Z
        restaurantGuid: e728cd53-2fa7-4e63-8f8f-93e78ea66b03
        externalGroupRef: externalGroupRef
      properties:
        restaurantGuid:
          description: |
            The unique Toast POS identifier for the restaurant.
          example: e728cd53-2fa7-4e63-8f8f-93e78ea66b03
          format: uuid
          type: string
        managementGroupGuid:
          description: |
            The guid of the management group containing the restaurant.
          example: bdfda703-2a83-4e0f-9b8a-8ea0ee6cab79
          format: uuid
          type: string
        deleted:
          description: "Indicates whether the restaurant is actively using the Toast\
            \ \nplatform. For example, if a restaurant is no longer operating, \n\
            or is no longer using the Toast platform, this value is `true`.\n"
          type: boolean
        restaurantName:
          description: |
            The human-readable name of the restaurant location.
          example: Main Street Cafe
          type: string
        locationName:
          description: "The identifier of a specific restaurant location, set on the\
            \ \n*Restaurant Info* page of Toast Web. \nFor example, a restaurant group\
            \ might assign a location code \nsuch as #1234 to a specific location.\n"
          example: 123 Main Street
          type: string
        createdByEmailAddress:
          description: |
            The email address of the restaurant employee who connected the
            restaurant to your integrated partner service, or who edited the
            connection details.
          example: clefebvre@mainstreetcafe.com
          type: string
        externalGroupRef:
          description: |
            An identifier for the restaurant group that is recognized by your
            integrated partner service. This information is entered by the
            restaurant administrator. If you need information about the restaurant
            group in this data string, you instruct the restaurant administrator
            to enter it in the Toast platform configuration for the integration
            partner connection.
          type: string
        externalRestaurantRef:
          description: |
            An identifier for the restaurant location that is recognized by your
            integrated partner service. This information is entered by the
            restaurant administrator. If you need information about the restaurant
            location in this data string, you instruct the restaurant
            administrator to enter it in the Toast platform configuration for the
            integration partner connection.
          type: string
        modifiedDate:
          description: |
            The most recent date and time that the partner connection
            was edited in epoch time (milliseconds since 1970-01-01 00:00:00).
          example: 1678846869551
          format: int64
          type: integer
        createdDate:
          description: |
            The date and time that the partner connection was created in epoch
            time (milliseconds since 1970-01-01 00:00:00).
          example: 1643858534451
          format: int64
          type: integer
        isoModifiedDate:
          description: |
            The most recent date and time that the partner connection
            was edited in ISO8601 format.
          example: 2023-03-12T08:32:34.008Z
          type: string
        isoCreatedDate:
          description: |
            The date and time that the partner connection was created in ISO8601
            format.
          example: 2022-05-17T10:21:38.008Z
          type: string
      type: object
    PartnerAccessExternalWebhookRep:
      description: |
        Information about a Toast platform restaurant.
      properties:
        restaurantGuid:
          description: |
            The unique Toast platform identifier for the restaurant.
          example: e728cd53-2fa7-4e63-8f8f-93e78ea66b03
          format: uuid
          type: string
        managementGroupGuid:
          description: |
            The unique Toast platform identifier for the management group
            containing the restaurant.
          example: bdfda703-2a83-4e0f-9b8a-8ea0ee6cab79
          format: uuid
          type: string
        restaurantName:
          description: |
            The human-readable name of the restaurant location.
          type: string
        locationName:
          description: |
            The identifier of a specific restaurant location, set on the
            *Restaurant Info* page of Toast Web.
            For example, a restaurant group might assign a location code
            such as `Location1234` to a specific location.
          example: Location1234
          type: string
        externalGroupRef:
          description: |
            An identifier for the restaurant group that is recognized by your
            integrated partner service. This information is entered by the
            restaurant administrator. If you need information about the restaurant
            group in this data string, you instruct the restaurant administrator
            to enter it in the Toast platform configuration for the integration
            partner connection.
          type: string
        externalRestaurantRef:
          description: |
            An identifier for the restaurant location that is recognized by your
            integrated partner service. This information is entered by the
            restaurant administrator. If you need information about the restaurant
            location in this data string, you instruct the restaurant
            administrator to enter it in the Toast platform configuration for the
            integration partner connection.
          type: string
        modifiedDate:
          description: |
            The most recent date and time that the partner connection
            was edited in epoch time (milliseconds since 1970-01-01 00:00:00).
          example: 1678846869551
          format: int64
          type: integer
        createdDate:
          description: |
            The date and time that the partner connection was created in epoch time (milliseconds since 1970-01-01 00:00:00).
          example: 1643858534451
          format: int64
          type: integer
        isoModifiedDate:
          description: |
            The most recent date and time that the partner connection
            was edited in ISO8601 format.
          example: 2023-03-12T08:32:34.008Z
          type: string
        isoCreatedDate:
          description: |
            The date and time that the partner connection was created in ISO8601 format.
          example: 2022-05-17T10:21:38.008Z
          type: string
        createdByFirstName:
          description: |
            The first name of the restaurant employee who initiated the event.
          example: Clemence
          type: string
        createdByLastName:
          description: |
            The last name of the restaurant employee who initiated the event.
          example: Lefebvre
          type: string
        createdByEmailAddress:
          description: |
            The email address of the restaurant employee who connected the
            restaurant to your integrated partner service, or who edited the
            connection details.
          example: clefebvre@mainstreetcafe.com
          type: string
        createdByPhoneNumber:
          description: |
            The phone number of the user who initiated the event.
          example: "9876543210"
          type: string
        restaurantPhoneNumber:
          description: |
            The phone number of the restaurant.
          example: "8765432109"
          type: string
        restaurantAddressLine1:
          description: |
            The physical address of the restaurant location.
          example: 123 Main Street
          type: string
        restaurantAddressLine2:
          description: |
            Optional additional physical address of the restaurant location.
          example: Suite 321
          type: string
        restaurantCity:
          description: |
            The city in which the restaurant is located.
          example: Gatineau
          type: string
        restaurantState:
          description: |
            The state in which the restaurant is located.
          example: Massachusetts
          type: string
        restaurantZipCode:
          description: |
            The zip code of the restaurant location.
          example: "01234"
          type: string
        restaurantLatitude:
          description: |
            The latitude of the restaurant location.
          type: string
        restaurantLongitude:
          description: |
            The longitude of the restaurant location.
          type: string
        restaurantCountryCode:
          description: |
            The ISO 3166-1 alpha-2 country code of the restaurant location.
          example: US
          type: string
        restaurantTimezone:
          description: |
            The IANA time zone identifier of the restaurant location.
            For example, `America/New_York`.
          example: America/New_York
          type: string
      type: object
    PaginatedResponse:
      description: |
        A wrapper object containing paginated sets of response data. The `results`
        value is an array of `PartnerAccessExternalRep` objects, which hold
        information about Toast platform restaurants. Also includes pagination
        details such as how many pages are included in the response, or the total
        number of objects in the `results` array.
      example:
        currentPageNum: 1
        results:
        - restaurantGuid: 7ab295f6-8dc8-4cb6-8cdb-072b83e84184
          managementGroupGuid: 75063706-dd6e-4da6-8bb6-3a99e218e686
          restaurantName: Main Street Cafe
          locationName: 123 Main Street
          createdByEmailAddress: clefebvre@mainstreetcafe.com
          externalGroupRef: ""
          externalRestaurantRef: ""
          modifiedDate: 1678823073353
          createdDate: 1678823073353
          isoModifiedDate: 2023-03-14T19:44:33.353Z
          isoCreatedDate: 2023-03-14T19:44:33.353Z
        totalResultCount: 3222
        pageSize: 1
        currentPageToken: cDoxLHM6MQ==
        nextPageToken: cDoyLHM6MQ==
        totalCount: 3222
        nextPageNum: 2
        lastPageNum: 3222
      properties:
        currentPageNum:
          description: |
            The active page within all repsonse pages. You can see the total amount of pages at the end of the response in the `lastPageNum` field.
          example: 12
          type: integer
        results:
          description: |
            An array of `PartnerAccessExternalRep` objects that include
            information about Toast platform restaurants.
          items:
            $ref: "#/components/schemas/PartnerAccessExternalRep"
          type: array
        totalResultCount:
          description: |
            The total number of records returned.
          example: 1234
          type: integer
        pageSize:
          description: |
            The number of restaurants returned in each page of response data.
          example: 100
          type: integer
        currentPageToken:
          description: |
            A string that identifies the current page of response data.
          example: cDoxLHM6MQ==
          type: string
        nextPageToken:
          description: |
            A string that identifies the following page of response data.
          example: cDoyLHM6MQ==
          type: string
        totalCount:
          description: |
            The total number of results within the response record.
          example: 1234
          type: integer
        nextPageNum:
          description: |
            The next available page in the data. `Null` if the current page of
            results is the last available page.
          example: 14
          type: integer
        lastPageNum:
          description: |
            The last page number in the response data.
          example: 13
          type: integer
        previousPageNum:
          description: |
            The page number for the page previous to your current page in
            sequential order. `Null` if there are no pages previous to your
            current page.
          example: 12
          type: integer
      type: object
  securitySchemes:
    oauth2:
      description: "Access to Toast APIs, specific endpoints, \nand specific API endpoint\
        \ operations is \ncontrolled by the scopes that are associated \nwith your\
        \ API account. \nA full reference for Toast API scopes and \ntheir capabilities\
        \ can be found in the\n[_Toast Developer Guide_](https://doc.toasttab.com/doc/devguide/apiScopes.html).\n"
      flows:
        clientCredentials:
          scopes: {}
          tokenUrl: https://toast-api-server/authentication/v1/authentication/login
      type: oauth2
x-original-swagger-version: "2.0"
